# Generated by Django 6.0.6 on 2026-06-10 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refueling',
            name='price_per_liter',
            field=models.FloatField(default=55.0, verbose_name='Цена за 1 литр'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.fuelnetwork', verbose_name='Сеть АЗС'),
        ),
    ]
