# Generated by Django 6.0.6 on 2026-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_refueling_price_per_liter_alter_refueling_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelnetwork',
            name='default_price',
            field=models.FloatField(default=55.0, verbose_name='Цена за 1л (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='price_per_liter',
            field=models.FloatField(verbose_name='Цена за 1 литр'),
        ),
    ]
