# Generated by Django 6.0.6 on 2026-06-14 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_fuelnetwork_default_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelnetwork',
            name='default_price',
        ),
        migrations.AddField(
            model_name='fuelnetwork',
            name='price_92',
            field=models.FloatField(default=50.0, verbose_name='Цена 92'),
        ),
        migrations.AddField(
            model_name='fuelnetwork',
            name='price_95',
            field=models.FloatField(default=55.0, verbose_name='Цена 95'),
        ),
        migrations.AddField(
            model_name='fuelnetwork',
            name='price_diesel',
            field=models.FloatField(default=60.0, verbose_name='Цена ДТ'),
        ),
        migrations.AddField(
            model_name='refueling',
            name='fuel_type',
            field=models.CharField(choices=[('92', 'АИ-92'), ('95', 'АИ-95'), ('DT', 'Дизель')], default='95', max_length=10, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuelings', to='tracker.vehicle', verbose_name='Автомобиль'),
        ),
    ]
